### PR TITLE
add other commands

### PR DESCRIPTION
**Pull request by kovetskiy**
I'm added binding to commands. I think that's really easier for use than `<Plug>(blahbla)`

### CODE REVIEW

**Comment by t9md** [comment]
Thank you for your feedback.
It seems no problem the code you added.
But I'm not sure its useful since when you use swap and swap-again, its much easier to use mapping with '<plug>(' mapping rather than invoking command from command window.
Why you need explicit command for these operation?

**Comment by t9md** [comment]
I addes swap specific command in latest commit, its simply syntax sugar, and swap-again is now accomplished with swap and previous action. so, swap-previous key determined by whay key is mapped to `previous` action. default is `ss`.
Check latest doc or Radme.md

**Comment by kovetskiy** [comment]
I'm using commands for lazy loading plugins with vim-plug.

For example:
Plug 't9md/vim-choosewin', {'on': 'ChooseWinSwapAgain'}

**Comment by t9md** [comment]
Since ChooseWinSwapAgain is no longer available in latest code.
ChooseWinSwap is candidate for lazy loading.
If you use NeoBundle, its have feature to lazy load from virtual keycap like `<Plug>(choosewin)`

**Pull request closed without merging**
